#!/bin/bash
#
# U - user name, D - date
#
if [ "$1" = "" ]; then
    U="vbert"
    D=`date`
    MSG="$U, $D"
else
    MSG=$1
fi

# GIT:
git add .
git commit -a -m "$MSG"
git push origin master 
# --all
